# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "reframework-d2d"
cmake-after = "set(VCPKG_TARGET_TRIPLET x64-windows-static)"

[vcpkg]
version = "2022.01.01"
packages = ["sol2", "lua", "utfcpp"]

[find-package]
sol2 = { required = true, config = true }
Lua = { required = true }
utf8cpp = { required = true, config = true }

[target.reframework]
type = "interface"
include-directories = ["deps/reframework/include"]

[target.reframework-d2d]
type = "shared"
sources = ["src/**.cpp"]
headers = ["src/**.hpp"]
include-directories = ["${LUA_INCLUDE_DIR}"]
link-libraries = ["sol2::sol2", "${LUA_LIBRARIES}", "utf8cpp", "reframework", "d2d1", "dwrite", "d3d11", "d3d12", "dxgi", "d3dcompiler"]
compile-features = ["cxx_std_20"]
