name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    if: ${{github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository)}}

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: REFramework-D2D
          path: ${{github.workspace}}/build/{{env.BUILD_TYPE}}/reframework-d2d.dll
          if-no-files-found: error
